### ISSUE TITLE
Size of QR Code image

### ISSUE THREAD

**Issue by szonov** [ushelp/EasyQRCodeJS#18]
Depends on text passed to new QRCode every time I'm get different size of resulting image.
for example I set  width and height 256, but image has size 250 or even 261.
Is it possible to get exact size of resulting image as I requested?

**Comment by ushelp** [comment]
Hey @szonov ,

You need to know a basic principle,  the size you set does not  necessarily divide the count of blocks , it will produce a remainder, like
```JS
250/33 = 7.575757575757576
```
Such numbers cannot be drawn, so we must have adopt the rounding method. This is why size changes are normal.

So if you want to get a fixed size image, please make sure the size you set can to divide the count of blocks horizontally and vertically. Otherwise, size change cannot be avoided.

**Comment by szonov** [comment]
Hello, thank you
I've checked library code and adapt my code - just recalculate my width and height depends on blocks amount and additionally added padding (quietZone) to have image size as originally requested by my code (or 1 pixel less when quietZone is odd). 
Thank you again, issue can be closed
